# coding: utf-8

def load_examples():
	gpsr_examples = ["tell me how many beverages are in the shelf",
		"put the crackers on the kitchen table",
		"tell the time to ana at the bedroom",
		"tell me the name of the person at the door",
		"bring me the apple juice from the counter",
		"tell me how many beverages in the shelf are red",
		"put the banana on the kitchen table",
		"count the waving people in the livingroom",
		"follow ana at the entrance",
		"tell me the name of the woman in the kitchen",
		"pour some cereals in the bowl",
		"go to the bathroom",
		"bring me the milk from the microwave" ,
		"follow john", 
		"bring me a drink",
		"bring some snacks to mary",
		"find ana at the bedroom and tell her the time",
		"bring me a drink from the fridge",
		"follow me and then go to the kitchen",
		"give me the left most object from the shelf",
		"count the drinks on the table",
		"tell me how many girls there are in the livingroom",
		"place a coke onto the tray",
		"hand me a coke from the fridge",
		"bring me some flakes in a bowl",
		"put this book into the drawer",
		"turn off the tv",
		"put all the beverages on the dinner table",
		"bring me the biggest pill bottle from the kitchen counter",
		"bring me the bookcase’s right-most object",
		"describe the objects on the drawer to me",
		"tell me how many red apples are in the basket on the kitchen table",
		"count the snacks in the shelf and tell me how many there are",
		"guide the person at the entrance to the kitchen",
		"follow the person in front of you and go to the bedroom",
		"describe the person at the door",
		"ask joe to come here", 
		"take this coke to the girl wearing a red sweater",
		"take this coke to the girl in the living room wearing a red sweater",
		"tell me how many standing people there are in the dining room",
		"go to the living room and follow the waving person",
		"tell me what john is doing",
		"bring me a drink", 
		"guide a person to the kitchen", 
		"bring some snacks to the table",
		"bring me a coke from the fridge",
		"take ana from the sofa to her bed",
		"take the orange juice from the shelf and give it to mary",
		"bring me the coke from the fridge", 
		"check which beverages there are in the counter and offer one to james at the sofa",
		"go to the kitchen counter take the coke and bring it to me",
		"bring the chips to mary at the sofa tell the time and follow her",
		"find a person in the living room guide them to the kitchen and follow them",
		"take the chips from the counter find a person in the bedroom and go to the entrance",
		"where can i find elroy",
		"which kind of food should i give to him",
		"i can’t reach there what should i do now"
		"go to living room and find james" ,
		"go to living room and tell james to come here" ,
		"go to living room and tell james hello" ,
		"find james and bring him here" ,
		"find james and tell him i love you" ,
		"go to kitchen and say hello" ,
		"go to living room and say what the fuck" ,
		"go to kitchen and find james and tell him to go to living room" ,
		"go to kitchen and count people there ",
		"go to kitchen and find people ",
		"go to kitchen and count bottles" ,
		"find a person and tell him to help you" ,
		"find a person and say help me" ,
		"find a person and tell help me" ,
		"find a person and tell him to go to kitchen" ,
		"go to kitchen and count bottle" ,
		"count people and tell me how many people are here" ,
		"count people" ,
		"count person" ,
		"tell james to go to kitchen" ,
		"count bottle" ,
		"find person in living room ",
		"go to sitting people and tell him to stand up",
		"go to the people in living room and go to kitchen" 		
		]
	return gpsr_examples